const events = {
  COMMUNITY_CHAT: "COMMUNITY_CHAT",
  USER_CONNECTED: "USER_CONNECTED",
  VERIFY_USER: "VERIFY_USER",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_RECONNECTED: "USER_RECONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  MESSAGE_SENT: "MESSAGE_SENT",
  TYPING: "TYPING"
};

export default events;
