module.exports = {
  USER_CONNECTED: "USER_CONNECTED",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  MESSAGE_SENT: "MESSAGE_SENT",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  LOGOUT: "LOGOUT",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  TYPING: "TYPING",
  VERIFY_USER: "VERIFY_USER"
};
